services:
  db:
    build: 
      context: ./mysql
    image: lucasdamascena/mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - nodenet
    volumes:
      - ./mysql:/var/lib/mysql_shared
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: lucasdamascena/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodenet
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lucasdamascena/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  nodenet:
    driver: bridge
